import { ArrowLeft, Download, Eye, LoaderCircle } from 'lucide-react';
import { useParams, Link } from 'react-router-dom';
import { Alert, Badge, Button, Card } from '@/components/common';
import { EmptyState } from '@/components/tables';
import { type Invoice } from '@/services/billingApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { useInvoiceDetailsQuery, useInvoicePdfMutation } from '@/services/billingQueries';
import { money } from '@/lib/financial';

const statusTone = (status: Invoice['status']) => status === 'finalized' ? 'success' : status === 'approved' ? 'info' : status === 'review' ? 'info' : 'warning';

export function InvoiceDetailsPage() {
  const { id = '' } = useParams(); const invoiceQuery = useInvoiceDetailsQuery(id); const pdfMutation = useInvoicePdfMutation();
  const invoice = invoiceQuery.data; const error = invoiceQuery.error || pdfMutation.error;
  async function handlePdf(download: boolean) { if (!invoice || invoice.status !== 'finalized') return; try { const blob = await pdfMutation.mutateAsync(invoice._id); const url = URL.createObjectURL(blob); if (download) { const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${invoice.invoiceNumber ?? `invoice-${invoice._id}`}.pdf`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); } else { window.open(url, '_blank', 'noopener,noreferrer'); } window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } catch { /* Rendered through the mutation error. */ } }
  if (invoiceQuery.isLoading) return <div className="dashboard-loading">Loading invoice details...</div>;
  if (error || !invoice) return <Alert tone="error" title="Could not load invoice" onDismiss={() => void invoiceQuery.refetch()}>{error ? getApiErrorMessage(error) : 'Invoice details were not returned by the backend.'}</Alert>;
  const historical = invoice.status === 'finalized';
  if (!invoice.lineItems.length) return <div className="vehicle-page billing-page"><Link className="back-link" to="/billing/invoices"><ArrowLeft size={15} /> Back to invoice history</Link><div className="page-heading"><div><p className="eyebrow">Invoice detail</p><h1>{invoice.invoiceNumber ?? invoice._id}</h1><p className="muted">{invoice.month}/{invoice.year}</p></div><Badge tone={statusTone(invoice.status)}>{invoice.status}</Badge></div><Card title="Trip calculations"><EmptyState title="No trips are available for this billing period." description="This invoice contains no contributing trip rows from the backend." /></Card></div>;
  return <div className="vehicle-page billing-page"><Link className="back-link" to="/billing/invoices"><ArrowLeft size={15} /> Back to invoice history</Link><div className="page-heading"><div><p className="eyebrow">Invoice detail</p><h1>{invoice.invoiceNumber ?? invoice._id}</h1><p className="muted">{invoice.month}/{invoice.year} · {invoice.summary.tripCount} trips</p></div><div className="heading-actions"><Badge tone={statusTone(invoice.status)}>{invoice.status}</Badge>{historical && <><Button variant="secondary" loading={pdfMutation.isPending} icon={<Eye size={16} />} onClick={() => void handlePdf(false)} disabled={pdfMutation.isPending}>View PDF</Button><Button variant="secondary" loading={pdfMutation.isPending} icon={<Download size={16} />} onClick={() => void handlePdf(true)} disabled={pdfMutation.isPending}>Download PDF</Button></>}</div></div>{historical && <Alert tone="info" title="Historical finalized invoice">This invoice is a locked historical record. Values below come from the stored calculation snapshot and are not recalculated from current contracts or vehicle data.</Alert>}<Card title="Invoice totals" description="Values below are read from the stored invoice snapshots."><div className="billing-summary-strip"><div><span>Fuel</span><strong>{money.format(invoice.summary.fuelAmount)}</strong></div><div><span>Hiring</span><strong>{money.format(invoice.summary.hiringAmount)}</strong></div><div><span>Toll</span><strong>{money.format(invoice.summary.tollAmount)}</strong></div><div><span>Other</span><strong>{money.format(invoice.summary.otherBillableAmount)}</strong></div><div><span>Total</span><strong>{money.format(invoice.summary.totalAmount)}</strong></div></div></Card><Card title="Trip calculations" description={historical ? 'Historical trip calculations from the finalized invoice snapshot.' : 'Stored invoice calculation values.'}><div className="table-wrap"><table className="data-table billing-trip-table"><thead><tr><th>Date</th><th>Vehicle</th><th>Driver</th><th>Route</th><th>KM</th><th>Average</th><th>Fuel litres</th><th>Fuel</th><th>Hiring</th><th>Total</th></tr></thead><tbody>{invoice.lineItems.map((line) => <tr key={line._id ?? line.tripId}><td>{new Date(line.tripSnapshot.tripDate).toLocaleDateString()}</td><td>{line.tripSnapshot.vehicle.registrationNumber}</td><td>{line.tripSnapshot.driver.name}</td><td>{line.tripSnapshot.route?.name ?? `${line.tripSnapshot.pickupLocation} → ${line.tripSnapshot.dropLocation}`}</td><td>{line.snapshot.distanceKm}</td><td>{line.snapshot.contractualAverage}</td><td>{line.snapshot.fuelLitres}</td><td>{money.format(Number(line.snapshot.fuelAmount))}</td><td>{money.format(Number(line.snapshot.hiringAmount))}</td><td><strong>{money.format(Number(line.snapshot.totalAmount))}</strong></td></tr>)}</tbody></table></div></Card></div>;
}
