import { ArrowLeft, Save } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Button, Card } from '@/components/common';
import { TextInput, Textarea } from '@/components/forms';
import { firmsApi } from '@/services/firmsApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { FirmPayload } from '@/types';

export function FirmFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id);
  const [form, setForm] = useState<FirmPayload>({ name: '', billingName: '', gstNumber: '', address: { street: '', city: '', state: '', pinCode: '' }, contactDetails: { name: '', email: '', mobile: '' }, notes: '', isActive: true });
  const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!editing || !id) return; firmsApi.get(id).then((firm) => setForm({ name: firm.name, billingName: firm.billingName || '', gstNumber: firm.gstNumber || '', address: firm.address || {}, contactDetails: firm.contactDetails || {}, billingConfiguration: firm.billingConfiguration, notes: firm.notes || '', isActive: firm.isActive })).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [editing, id]);
  const update = (field: keyof FirmPayload, value: unknown) => setForm((current) => ({ ...current, [field]: value }));
  const updateNested = (group: 'address' | 'contactDetails', field: string, value: string) => setForm((current) => ({ ...current, [group]: { ...(current[group] || {}), [field]: value } }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!form.name.trim()) { setError('Firm name is required.'); return; } setSaving(true); try { if (editing && id) await firmsApi.update(id, form); else await firmsApi.create(form); notify.success(editing ? 'Firm updated.' : 'Firm added.'); navigate('/firms'); } catch (caught) { setError(getApiErrorMessage(caught)); notify.error(caught); } finally { setSaving(false); } }
  if (loading) return <div className="route-loading">Loading firm...</div>;
  return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/firms"><ArrowLeft size={15} /> Firms</Link><p className="eyebrow">Commercial setup</p><h1>{editing ? 'Edit firm' : 'Add firm'}</h1><p className="muted">Keep billing identity, contact, and tax information in one place.</p></div></div>{error && <Alert tone="error" title="Unable to save firm">{error}</Alert>}<form onSubmit={submit} className="vehicle-form-grid"><Card title="Firm identity" description="Names used for operations and billing records."><div className="form-grid"><TextInput id="name" label="Firm name" required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Enter firm name" /><TextInput id="billingName" label="Billing name" value={form.billingName || ''} onChange={(event) => update('billingName', event.target.value)} placeholder="Name printed on bills" /><TextInput id="gstNumber" label="GST / tax number" value={form.gstNumber || ''} onChange={(event) => update('gstNumber', event.target.value)} placeholder="Optional tax identifier" /></div></Card><Card title="Contact details"><div className="form-grid"><TextInput id="contactName" label="Contact name" value={form.contactDetails?.name || ''} onChange={(event) => updateNested('contactDetails', 'name', event.target.value)} /><TextInput id="contactEmail" label="Email" type="email" value={form.contactDetails?.email || ''} onChange={(event) => updateNested('contactDetails', 'email', event.target.value)} /><TextInput id="contactMobile" label="Mobile" value={form.contactDetails?.mobile || ''} onChange={(event) => updateNested('contactDetails', 'mobile', event.target.value)} /></div></Card><Card title="Address"><div className="form-grid"><TextInput id="street" label="Street" value={form.address?.street || ''} onChange={(event) => updateNested('address', 'street', event.target.value)} /><TextInput id="city" label="City" value={form.address?.city || ''} onChange={(event) => updateNested('address', 'city', event.target.value)} /><TextInput id="state" label="State" value={form.address?.state || ''} onChange={(event) => updateNested('address', 'state', event.target.value)} /><TextInput id="pinCode" label="PIN code" value={form.address?.pinCode || ''} onChange={(event) => updateNested('address', 'pinCode', event.target.value)} /></div></Card><Card title="Notes"><Textarea id="notes" label="Internal notes" value={form.notes || ''} onChange={(event) => update('notes', event.target.value)} /></Card><div className="form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/firms')}>Cancel</Button><Button type="submit" loading={saving} icon={<Save size={16} />}>{editing ? 'Save changes' : 'Add firm'}</Button></div></form></div>;
}