import { ArrowLeft, Edit3, Mail, MapPin, Phone } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Badge, Button, Card, LoadingSpinner, StatusBadge } from '@/components/common';
import { firmsApi } from '@/services/firmsApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { Firm } from '@/types';

export function FirmDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [firm, setFirm] = useState<Firm | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!id) return; firmsApi.get(id).then(setFirm).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [id]);
  async function toggleStatus() { if (!firm) return; try { await firmsApi.update(firm._id, { isActive: !firm.isActive }); setFirm({ ...firm, isActive: !firm.isActive }); notify.success(firm.isActive ? 'Firm deactivated.' : 'Firm activated.'); } catch (caught) { notify.error(caught); } }
  if (loading) return <div className="route-loading"><LoadingSpinner label="Loading firm details" /></div>;
  if (error || !firm) return <div className="vehicle-page"><Alert tone="error" title="Firm unavailable">{error || 'This firm could not be found.'}</Alert><Button variant="secondary" onClick={() => navigate('/firms')}>Back to firms</Button></div>;
  const address = [firm.address?.street, firm.address?.city, firm.address?.state, firm.address?.pinCode].filter(Boolean).join(', ');
  return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/firms"><ArrowLeft size={15} /> Firms</Link><p className="eyebrow">Firm record</p><h1>{firm.name}</h1><p className="muted">{firm.billingName || 'No billing name configured'}</p></div><div className="heading-actions"><Button variant="secondary" icon={<Edit3 size={16} />} onClick={() => navigate(`/firms/${firm._id}/edit`)}>Edit firm</Button><Button variant={firm.isActive ? 'danger' : 'primary'} onClick={() => void toggleStatus()}>{firm.isActive ? 'Deactivate' : 'Activate'}</Button></div></div><div className="detail-grid"><Card title="Firm identity"><div className="detail-list"><div><span>Firm name</span><strong>{firm.name}</strong></div><div><span>Billing name</span><strong>{firm.billingName || 'Not set'}</strong></div><div><span>GST / tax</span><strong>{firm.gstNumber || 'Not set'}</strong></div><div><span>Status</span><StatusBadge status={firm.isActive ? 'active' : 'inactive'} /></div></div></Card><Card title="Contact"><div className="detail-list"><div><span><Phone size={13} /> Mobile</span><strong>{firm.contactDetails?.mobile || 'Not set'}</strong></div><div><span><Mail size={13} /> Email</span><strong>{firm.contactDetails?.email || 'Not set'}</strong></div><div><span>Contact person</span><strong>{firm.contactDetails?.name || 'Not set'}</strong></div></div></Card><Card title="Address"><div className="detail-placeholder"><MapPin size={20} /><p>{address || 'No address added.'}</p></div></Card><Card title="Billing configuration" description="Detailed contract and rate configuration is managed through the Contracts module."><div className="detail-placeholder"><Badge tone={firm.billingConfiguration && Object.keys(firm.billingConfiguration).length ? 'success' : 'neutral'}>{firm.billingConfiguration && Object.keys(firm.billingConfiguration).length ? 'Configuration available' : 'No configuration'}</Badge><p>Firm-level billing configuration is displayed only when provided by the backend.</p></div></Card><Card title="Notes"><p className="muted">{firm.notes || 'No internal notes.'}</p></Card></div></div>;
}