import { ArrowLeft, Edit3, MapPin, Ruler, Signpost } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Badge, Button, Card, LoadingSpinner, StatusBadge } from '@/components/common';
import { routesApi } from '@/services/routesApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { Route } from '@/types';

export function RouteDetailsPage() { const { id } = useParams(); const navigate = useNavigate(); const [route, setRoute] = useState<Route | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { if (!id) return; routesApi.get(id).then(setRoute).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [id]); async function toggleStatus() { if (!route) return; try { await routesApi.update(route._id, { isActive: !route.isActive }); setRoute({ ...route, isActive: !route.isActive }); notify.success(route.isActive ? 'Route deactivated.' : 'Route activated.'); } catch (caught) { notify.error(caught); } } if (loading) return <div className="route-loading"><LoadingSpinner label="Loading route details" /></div>; if (error || !route) return <div className="vehicle-page"><Alert tone="error" title="Route unavailable">{error || 'This route could not be found.'}</Alert><Button variant="secondary" onClick={() => navigate('/routes')}>Back to routes</Button></div>; return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/routes"><ArrowLeft size={15} /> Routes</Link><p className="eyebrow">Route record</p><h1>{route.name}</h1><p className="muted">{route.routeCode || 'No route code configured'}</p></div><div className="heading-actions"><Button variant="secondary" icon={<Edit3 size={16} />} onClick={() => navigate(`/routes/${route._id}/edit`)}>Edit route</Button><Button variant={route.isActive ? 'danger' : 'primary'} onClick={() => void toggleStatus()}>{route.isActive ? 'Deactivate' : 'Activate'}</Button></div></div><div className="detail-grid"><Card title="Route details"><div className="detail-list"><div><span><MapPin size={13} /> Pickup</span><strong>{route.pickupLocation}</strong></div><div><span><Signpost size={13} /> Drop</span><strong>{route.dropLocation}</strong></div><div><span><Ruler size={13} /> Expected distance</span><strong>{route.expectedDistanceKm !== undefined ? `${route.expectedDistanceKm} km` : 'Not set'}</strong></div><div><span>Status</span><StatusBadge status={route.isActive ? 'active' : 'inactive'} /></div></div></Card><Card title="Intermediate stops"><div className="detail-placeholder">{route.intermediateStops?.length ? <div className="stop-list">{route.intermediateStops.map((stop, index) => <div className="stop-item" key={`${stop}-${index}`}><span>{String(index + 1).padStart(2, '0')}</span><strong>{stop}</strong></div>)}</div> : <><Badge tone="neutral">No intermediate stops</Badge><p>Only pickup and drop are configured for this route.</p></>}</div></Card><Card title="Notes"><p className="muted">{route.notes || 'No notes added.'}</p></Card></div></div>; }