import { ArrowLeft, Save } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Button, Card } from '@/components/common';
import { NumberInput, TextInput, Textarea } from '@/components/forms';
import { routesApi } from '@/services/routesApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { RoutePayload } from '@/types';

export function RouteFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [form, setForm] = useState<RoutePayload>({ name: '', routeCode: '', pickupLocation: '', dropLocation: '', intermediateStops: [], expectedDistanceKm: undefined, notes: '', isActive: true }); const [stopsText, setStopsText] = useState(''); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!editing || !id) return; routesApi.get(id).then((route) => { setForm({ name: route.name, routeCode: route.routeCode || '', pickupLocation: route.pickupLocation, dropLocation: route.dropLocation, intermediateStops: route.intermediateStops || [], expectedDistanceKm: route.expectedDistanceKm, notes: route.notes || '', isActive: route.isActive }); setStopsText((route.intermediateStops || []).join(', ')); }).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [editing, id]);
  const update = (field: keyof RoutePayload, value: unknown) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!form.name.trim() || !form.pickupLocation.trim() || !form.dropLocation.trim()) { setError('Route name, pickup location, and drop location are required.'); return; } if (form.expectedDistanceKm !== undefined && form.expectedDistanceKm < 0) { setError('Expected distance cannot be negative.'); return; } const intermediateStops = stopsText.split(',').map((stop) => stop.trim()).filter(Boolean); setSaving(true); try { const payload = { ...form, intermediateStops }; if (editing && id) await routesApi.update(id, payload); else await routesApi.create(payload); notify.success(editing ? 'Route updated.' : 'Route added.'); navigate('/routes'); } catch (caught) { setError(getApiErrorMessage(caught)); notify.error(caught); } finally { setSaving(false); } }
  if (loading) return <div className="route-loading">Loading route...</div>;
  return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/routes"><ArrowLeft size={15} /> Routes</Link><p className="eyebrow">Network</p><h1>{editing ? 'Edit route' : 'Add route'}</h1><p className="muted">Define a reusable movement pattern for trip entry.</p></div></div>{error && <Alert tone="error" title="Unable to save route">{error}</Alert>}<form onSubmit={submit} className="vehicle-form-grid"><Card title="Route identity" description="Use a clear name and optional internal code."><div className="form-grid"><TextInput id="name" label="Route name" required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Depot to customer" /><TextInput id="routeCode" label="Route code" value={form.routeCode || ''} onChange={(event) => update('routeCode', event.target.value)} placeholder="Optional code" /><TextInput id="pickupLocation" label="Pickup location" required value={form.pickupLocation} onChange={(event) => update('pickupLocation', event.target.value)} /><TextInput id="dropLocation" label="Drop location" required value={form.dropLocation} onChange={(event) => update('dropLocation', event.target.value)} /><NumberInput id="expectedDistanceKm" label="Expected distance (km)" min={0} step="any" value={form.expectedDistanceKm ?? ''} onChange={(event) => update('expectedDistanceKm', event.target.value === '' ? undefined : Number(event.target.value))} /></div></Card><Card title="Intermediate information" description="Separate stops with commas. These remain operational route information."><Textarea id="intermediateStops" label="Intermediate stops" value={stopsText} onChange={(event) => setStopsText(event.target.value)} placeholder="e.g. Stop one, Stop two" /><Textarea id="notes" label="Notes" value={form.notes || ''} onChange={(event) => update('notes', event.target.value)} /></Card><div className="form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/routes')}>Cancel</Button><Button type="submit" loading={saving} icon={<Save size={16} />}>{editing ? 'Save changes' : 'Add route'}</Button></div></form></div>;
}