import { ArrowLeft, Save } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Button, Card } from '@/components/common';
import { TextInput, Textarea } from '@/components/forms';
import { FirmSelector } from '@/components/business';
import { contractsApi } from '@/services/contractsApi';
import { firmsApi } from '@/services/firmsApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { ContractPayload, Firm } from '@/types';

export function ContractFormPage() { const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [firms, setFirms] = useState<Firm[]>([]); const [form, setForm] = useState<ContractPayload>({ firmId: '', name: '', description: '', isActive: true }); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); useEffect(() => { Promise.all([firmsApi.list({ page: 1, limit: 100, isActive: true }), editing && id ? contractsApi.get(id) : Promise.resolve(null)]).then(([firmPage, contract]) => { setFirms(firmPage.data); if (contract) setForm({ firmId: contract.firmId, companyId: contract.companyId, name: contract.name, description: contract.description || '', isActive: contract.isActive }); }).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [editing, id]); const update = (field: keyof ContractPayload, value: unknown) => setForm((current) => ({ ...current, [field]: value })); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!form.firmId || !form.name.trim()) { setError('Firm and contract name are required.'); return; } setSaving(true); try { if (editing && id) await contractsApi.update(id, form); else await contractsApi.create(form); notify.success(editing ? 'Contract updated.' : 'Contract added.'); navigate('/contracts'); } catch (caught) { setError(getApiErrorMessage(caught)); notify.error(caught); } finally { setSaving(false); } } if (loading) return <div className="route-loading">Loading contract...</div>; return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/contracts"><ArrowLeft size={15} /> Contracts</Link><p className="eyebrow">Commercial setup</p><h1>{editing ? 'Edit contract' : 'Add contract'}</h1><p className="muted">Contract metadata can be updated here. Billing rules are added as immutable versions.</p></div></div>{error && <Alert tone="error" title="Unable to save contract">{error}</Alert>}<form onSubmit={submit} className="vehicle-form-grid"><Card title="Contract information"><FirmSelector value={form.firmId} options={firms.map((firm) => ({ value: firm._id, label: firm.name }))} onChange={(value) => update('firmId', value)} error={!form.firmId && error ? 'Select a firm' : undefined} /><TextInput id="name" label="Contract name / reference" required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Annual transport agreement" /><Textarea id="description" label="Description" value={form.description || ''} onChange={(event) => update('description', event.target.value)} /></Card><div className="form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/contracts')}>Cancel</Button><Button type="submit" loading={saving} icon={<Save size={16} />}>{editing ? 'Save changes' : 'Add contract'}</Button></div></form></div>; }