import { ArrowLeft, Save } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Button, Card } from '@/components/common';
import { DateInput, NumberInput, Textarea, TextInput } from '@/components/forms';
import { driversApi } from '@/services/driversApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { DriverPayload } from '@/types';

export function DriverFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id);
  const [form, setForm] = useState<DriverPayload>({ name: '', mobile: '', employeeId: '', joiningDate: '', dailyWage: 0, notes: '', isActive: true }); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!editing || !id) return; driversApi.get(id).then((driver) => setForm({ name: driver.name, mobile: driver.mobile, employeeId: driver.employeeId || '', joiningDate: driver.joiningDate ? driver.joiningDate.slice(0, 10) : '', dailyWage: Number(typeof driver.dailyWage === 'object' ? driver.dailyWage.$numberDecimal : driver.dailyWage), isActive: driver.isActive, notes: driver.notes || '' })).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [editing, id]);
  const update = (field: keyof DriverPayload, value: unknown) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!form.name.trim() || !form.mobile.trim() || form.dailyWage < 0) { setError('Name, mobile, and a non-negative daily wage are required.'); return; } setSaving(true); try { const payload = { ...form, joiningDate: form.joiningDate ? new Date(`${form.joiningDate}T00:00:00.000Z`).toISOString() : undefined }; if (editing && id) await driversApi.update(id, payload); else await driversApi.create(payload); notify.success(editing ? 'Driver updated.' : 'Driver added.'); navigate('/drivers'); } catch (caught) { setError(getApiErrorMessage(caught)); notify.error(caught); } finally { setSaving(false); } }
  if (loading) return <div className="route-loading">Loading driver...</div>;
  return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/drivers"><ArrowLeft size={15} /> Drivers</Link><p className="eyebrow">People</p><h1>{editing ? 'Edit driver' : 'Add driver'}</h1><p className="muted">A driver can operate different vehicles over time. Assignments belong to trips.</p></div></div>{error && <Alert tone="error" title="Unable to save driver">{error}</Alert>}<form onSubmit={submit} className="vehicle-form-grid"><Card title="Driver information" description="Contact and reference information for the driver."><div className="form-grid"><TextInput id="name" label="Full name" required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Rajesh Kumar" /><TextInput id="mobile" label="Mobile number" required value={form.mobile} onChange={(event) => update('mobile', event.target.value)} placeholder="e.g. +919876543210" /><TextInput id="employeeId" label="Employee / reference ID" value={form.employeeId || ''} onChange={(event) => update('employeeId', event.target.value)} placeholder="Optional reference" /><DateInput id="joiningDate" label="Joining date" value={form.joiningDate || ''} onChange={(event) => update('joiningDate', event.target.value)} /></div></Card><Card title="Wage and notes" description="The daily wage is stored as the driver's current rate."><NumberInput id="dailyWage" label="Daily wage" required min={0} step="0.01" value={form.dailyWage || ''} onChange={(event) => update('dailyWage', Number(event.target.value))} /><Textarea id="notes" label="Notes" value={form.notes || ''} onChange={(event) => update('notes', event.target.value)} placeholder="Optional operational notes" /></Card><div className="form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/drivers')}>Cancel</Button><Button type="submit" loading={saving} icon={<Save size={16} />}>{editing ? 'Save changes' : 'Add driver'}</Button></div></form></div>;
}