import { ArrowLeft, Edit3, MapPin, Truck, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Badge, Button, Card, LoadingSpinner, StatusBadge } from '@/components/common';
import { driversApi } from '@/services/driversApi';
import { tripsApi } from '@/services/tripsApi';
import { getApiErrorMessage } from '@/services/apiClient';
import { notify } from '@/lib/toast';
import type { Driver, Trip } from '@/types';

const decimalText = (value: Driver['dailyWage']) => typeof value === 'object' ? value.$numberDecimal || '-' : String(value);
export function DriverDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [driver, setDriver] = useState<Driver | null>(null); const [trips, setTrips] = useState<Trip[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!id) return; Promise.all([driversApi.get(id), tripsApi.list({ driverId: id, page: 1, limit: 10 })]).then(([driverData, tripPage]) => { setDriver(driverData); setTrips(tripPage.data); }).catch((caught) => setError(getApiErrorMessage(caught))).finally(() => setLoading(false)); }, [id]);
  async function toggleStatus() { if (!driver) return; try { await driversApi.update(driver._id, { isActive: !driver.isActive }); setDriver({ ...driver, isActive: !driver.isActive }); notify.success(driver.isActive ? 'Driver deactivated.' : 'Driver activated.'); } catch (caught) { notify.error(caught); } }
  if (loading) return <div className="route-loading"><LoadingSpinner label="Loading driver details" /></div>;
  if (error || !driver) return <div className="vehicle-page"><Alert tone="error" title="Driver unavailable">{error || 'This driver could not be found.'}</Alert><Button variant="secondary" onClick={() => navigate('/drivers')}>Back to drivers</Button></div>;
  const vehicleIds = [...new Set(trips.map((trip) => trip.vehicleId))];
  return <div className="vehicle-page"><div className="page-heading"><div><Link className="back-link" to="/drivers"><ArrowLeft size={15} /> Drivers</Link><p className="eyebrow">Driver record</p><h1>{driver.name}</h1><p className="muted">{driver.employeeId || 'No reference ID'} · {driver.mobile}</p></div><div className="heading-actions"><Button variant="secondary" icon={<Edit3 size={16} />} onClick={() => navigate(`/drivers/${driver._id}/edit`)}>Edit driver</Button><Button variant={driver.isActive ? 'danger' : 'primary'} onClick={() => void toggleStatus()}>{driver.isActive ? 'Deactivate' : 'Activate'}</Button></div></div><div className="detail-grid"><Card title="Basic information"><div className="detail-list"><div><span>Name</span><strong>{driver.name}</strong></div><div><span>Contact</span><strong>{driver.mobile}</strong></div><div><span>Reference ID</span><strong>{driver.employeeId || 'Not set'}</strong></div><div><span>Joining date</span><strong>{driver.joiningDate ? new Date(driver.joiningDate).toLocaleDateString() : 'Not set'}</strong></div><div><span>Daily wage</span><strong>₹ {decimalText(driver.dailyWage)}</strong></div><div><span>Status</span><StatusBadge status={driver.isActive ? 'active' : 'inactive'} /></div></div></Card><Card title="Vehicle history" description="Vehicles are shown from trip assignments. No permanent driver-vehicle relationship is assumed."><div className="detail-list"><div><span>Vehicles operated</span><strong>{vehicleIds.length}</strong></div><div><span>Recent assignments</span><strong>{trips.length}</strong></div></div>{trips.length ? <div className="trip-list">{trips.map((trip) => <div className="trip-row" key={trip._id}><span className="trip-date">{new Date(trip.tripDate).toLocaleDateString()}</span><span><Truck size={13} /> {trip.vehicleId}</span><span><MapPin size={13} /> {trip.pickupLocation} → {trip.dropLocation}</span><StatusBadge status={trip.operationalStatus} /></div>)}</div> : <div className="detail-placeholder"><UserRound size={20} /><p>No trip assignments are available for this driver yet.</p></div>}</Card><Card title="Driver history" actions={<Badge tone="neutral">{driver.history?.length || 0} events</Badge>}>{driver.history?.length ? <div className="history-list">{driver.history.map((event, index) => <div className="history-row" key={`${event.eventType}-${index}`}><StatusBadge status={event.eventType} /><span>{event.date ? new Date(event.date).toLocaleDateString() : 'No date'}</span><p>{event.notes || 'No notes'}</p></div>)}</div> : <div className="detail-placeholder"><p>No history events recorded.</p></div>}</Card></div></div>;
}